version: '3.8'
services:
  qk_front:
    command: dev
    volumes:
      - ./qk-front/:/usr/src/app
  qk_processing:
    build:
      context: ./qk-processing/
    command: npm run start:dev
    volumes:
      - ./qk-processing/:/app