version: '3.8'
services:
  qk-front:
    container_name: qk_front
    build:
      context: ./qk-front/
    ports:
      - 3000:3000

  qk-processing:
    container_name: qk_processing
    ports:
      - 3001:3001
      - 9229:9229
    env_file:
      - ./qk-processing/.env
    networks:
      - qualkey
    depends_on:
      - qualkey-db

  qualkey-db:
    container_name: qualkey_db
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: qualkey
      POSTGRES_PASSWORD: qualkey
      POSTGRES_DB: qualkey
    networks:
      - qualkey
    volumes:
      - pgdata:/var/lib/postgresql/data
networks:
  qualkey:
volumes:
  pgdata: